// Code generated by "stringer -type=OrderEventKind"; DO NOT EDIT.

package zeroex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EKInvalid-0]
	_ = x[EKOrderAdded-1]
	_ = x[EKOrderFilled-2]
	_ = x[EKOrderFullyFilled-3]
	_ = x[EKOrderCancelled-4]
	_ = x[EKOrderExpired-5]
	_ = x[EKOrderBecameUnfunded-6]
	_ = x[EKOrderFillabilityIncreased-7]
}

const _OrderEventKind_name = "EKInvalidEKOrderAddedEKOrderFilledEKOrderFullyFilledEKOrderCancelledEKOrderExpiredEKOrderBecameUnfundedEKOrderFillabilityIncreased"

var _OrderEventKind_index = [...]uint8{0, 9, 21, 34, 52, 68, 82, 103, 130}

func (i OrderEventKind) String() string {
	if i >= OrderEventKind(len(_OrderEventKind_index)-1) {
		return "OrderEventKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderEventKind_name[_OrderEventKind_index[i]:_OrderEventKind_index[i+1]]
}
