version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "development"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "development"
  - package-ecosystem: "docker"
    directory: "/dockerfiles/mesh"
    schedule:
      interval: "daily"
    target-branch: "development"
  - package-ecosystem: "docker"
    directory: "/dockerfiles/mesh-bootstrap"
    schedule:
      interval: "daily"
    target-branch: "development"
  - package-ecosystem: "docker"
    directory: "/dockerfiles/mesh-bridge"
    schedule:
      interval: "daily"
    target-branch: "development"
  - package-ecosystem: "docker"
    directory: "/dockerfiles/mesh-fluentbit"
    schedule:
      interval: "daily"
    target-branch: "development"
