linters:
  disable-all: false
  enable:
      # Finds repeated strings that could be made constants
      - goconst
      # Identifies commonly misspelled words
      - misspell
      # Ensures that the code was formatted with `gofmt -s`
      - gofmt
