linters:
  disable-all: false
  enable:
      # Finds repeated strings that could be made constants
      - goconst
      # Ensures that the code was formatted with `gofmt -s`
      - gofmt
      # Identifies commonly misspelled words
      - misspell
      # Identifies unused function parameters
      - unparam
      # Inspects source code for security problems by scanning the Go AST.
      - gosec
