const path = require('path');

module.exports = {
    entry: './src/index.ts',
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: /node_modules/,
            },
        ],
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
    },
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist'),
    },
    // This supports the ethereumjs-vm dependency in `@0x/base-contract` 
    // The .wasm 'glue' code generated by Emscripten requires these node builtins,
    // but won't actually use them in a web environment. We tell Webpack to not resolve those
    // require statements since we know we won't need them.
    externals: {
        fs: true,
    },
};
