#!/bin/bash
# Copyright 2018 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the GO_LICENSE file.
# Modified work copyright 2019 Alex Browne.

# Check Node.js version
if [[ $(node --version) =~ v([0-9]|10)\. ]]
then
	echo "Node.js version >= 11 is required"
	exit 1
fi

# We changed this line to require our node_shim.js.
exec node --require=$ZEROEX_MESH_ROOT_DIR/test-wasm/node_shim.js "$(go env GOROOT)/misc/wasm/wasm_exec.js" "$@"
